# Docker Compose SIMPLE para Ghost

services:
  ghost:
    image: ghost:latest
    ports:
      - "2368:2368"
    environment:
      url: http://localhost:2368
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      database__useNullAsDefault: true
      database__debug: false
    volumes:
      - ghost_data:/var/lib/ghost/content

volumes:
  ghost_data:
