services:
  - type: web
    name: ghost-blog
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free  # Plan gratuito específico
    envVars:
      - key: NODE_ENV
        value: production
      # Configuración Supabase PostgreSQL - latinhub-blog-db
      - key: DATABASE_CLIENT
        value: pg
      - key: DATABASE_HOST
        value: db.pepkpgvnhpqwgwpaiqua.supabase.co
      - key: DATABASE_USER
        value: postgres
      - key: DATABASE_PASSWORD
        value: YOUR_SUPABASE_PASSWORD_HERE
      - key: DATABASE_NAME
        value: postgres
      - key: DATABASE_PORT
        value: "5432"
      - key: DATABASE_SSL
        value: "true"
      - key: mail__transport
        value: Direct
      - key: mail__from
        value: noreply@yourdomain.com
      - key: url
        value: https://blog.latinhub.info
    # NOTA: No necesitamos disco persistente - datos en Supabase PostgreSQL
